// Configuration for API endpoints and sensitive data
// Uses environment variables for production builds to obfuscate sensitive information

export const config = {
  // Contact is form-only (Formspree) — no public email on the client
  
  // Audio file URLs (obfuscated in production)
  AUDIO_FILES: {
    SHADOWS: import.meta.env.VITE_AUDIO_SHADOWS || 'https://linturomusic.s3.us-west-2.amazonaws.com/shadows.WAV',
    DOWN_AGAIN: import.meta.env.VITE_AUDIO_DOWN_AGAIN || 'https://linturomusic.s3.us-west-2.amazonaws.com/downAgain.WAV',
    ETERNITY: import.meta.env.VITE_AUDIO_ETERNITY || 'https://linturomusic.s3.us-west-2.amazonaws.com/eternity.WAV',
    THE_LIGHT: import.meta.env.VITE_AUDIO_THE_LIGHT || 'https://linturomusic.s3.us-west-2.amazonaws.com/theLight.WAV',
    PROUD: import.meta.env.VITE_AUDIO_PROUD || 'https://linturomusic.s3.us-west-2.amazonaws.com/proud.WAV',
    THE_DEEPEST_HOUSE: import.meta.env.VITE_AUDIO_THE_DEEPEST_HOUSE || 'https://linturomusic.s3.us-west-2.amazonaws.com/theDeepestHouse.WAV',
    RECHARGE: import.meta.env.VITE_AUDIO_RECHARGE || 'https://linturomusic.s3.us-west-2.amazonaws.com/recharge.WAV',
    REFLECTIONS: import.meta.env.VITE_AUDIO_REFLECTIONS || 'https://linturomusic.s3.us-west-2.amazonaws.com/reflections.WAV',
    LONG_ROAD: import.meta.env.VITE_AUDIO_LONG_ROAD || 'https://linturomusic.s3.us-west-2.amazonaws.com/longroad-master.mp3',
    REC059: import.meta.env.VITE_AUDIO_REC059 || 'https://linturomusic.s3.us-west-2.amazonaws.com/rec059-master.mp3',
    INFINITY: import.meta.env.VITE_AUDIO_INFINITY || 'https://linturomusic.s3.us-west-2.amazonaws.com/infinity.WAV',
    LETS_GET_DOWN: import.meta.env.VITE_AUDIO_LETS_GET_DOWN || 'https://linturomusic.s3.us-west-2.amazonaws.com/letsGetDown.WAV',
    ECHOES: import.meta.env.VITE_AUDIO_ECHOES || 'https://linturomusic.s3.us-west-2.amazonaws.com/echoes.WAV',
    SUMMER_HEAT: import.meta.env.VITE_AUDIO_SUMMER_HEAT || 'https://linturomusic.s3.us-west-2.amazonaws.com/summerHeat.WAV',
    COLORS: import.meta.env.VITE_AUDIO_COLORS || 'https://linturomusic.s3.us-west-2.amazonaws.com/colors.WAV',
    TAKING_OFF: import.meta.env.VITE_AUDIO_TAKING_OFF || 'https://linturomusic.s3.us-west-2.amazonaws.com/takingOff.WAV',
    SET7: import.meta.env.VITE_AUDIO_SET7 || 'https://linturomusic.s3.us-west-2.amazonaws.com/springShowers.WAV',
    SET2: import.meta.env.VITE_AUDIO_SET2 || 'https://linturomusic.s3.us-west-2.amazonaws.com/newnew.WAV',
    SET4: import.meta.env.VITE_AUDIO_SET4 || 'https://linturomusic.s3.us-west-2.amazonaws.com/deepHaus.WAV',
    SET5: import.meta.env.VITE_AUDIO_SET5 || 'https://linturomusic.s3.us-west-2.amazonaws.com/minimalHaus.WAV',
    SET6: import.meta.env.VITE_AUDIO_SET6 || 'https://linturomusic.s3.us-west-2.amazonaws.com/summerRays.WAV',
    SUMMER_SESSIONS: import.meta.env.VITE_AUDIO_SUMMER_SESSIONS || 'https://linturomusic.s3.us-west-2.amazonaws.com/summerSessions.WAV',
    ORGANIC_HOUSE: import.meta.env.VITE_AUDIO_ORGANIC_HOUSE || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/organichousemix.mp3',
    LAST_OF_PASTEL: import.meta.env.VITE_AUDIO_LAST_OF_PASTEL || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/lastopasto.mp3',
    RAINDROPS: import.meta.env.VITE_AUDIO_RAINDROPS || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/raindropsarefalling.mp3',
    MIDSUMMER_DEPTHS: import.meta.env.VITE_AUDIO_MIDSUMMER_DEPTHS || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/jul25deephouse.mp3',
    HORIZON_LINE: import.meta.env.VITE_AUDIO_HORIZON_LINE || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/818deepprog.mp3',
    GET_SOME_3: import.meta.env.VITE_AUDIO_GET_SOME_3 || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/getsome3.mp3',
    CLOSED_CIRCUIT: import.meta.env.VITE_AUDIO_CLOSED_CIRCUIT || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/loops.mp3',
    MOONLIT_SKIES: import.meta.env.VITE_AUDIO_MOONLIT_SKIES || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/moonlitskyes.mp3',
    SECOND_PROGRESSION: import.meta.env.VITE_AUDIO_SECOND_PROGRESSION || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/prog2.mp3',
    GET_SOME: import.meta.env.VITE_AUDIO_GET_SOME || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/getsome.mp3',
    AUGUST_BLOOM: import.meta.env.VITE_AUDIO_AUGUST_BLOOM || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/proghouseaug8.mp3',
    JULY_HOUSE: import.meta.env.VITE_AUDIO_JULY_HOUSE || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/julyhouseset.mp3',
    JUNE_TECH: import.meta.env.VITE_AUDIO_JUNE_TECH || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/techhousejune.mp3',
    UPTEMPO_HOUSE: import.meta.env.VITE_AUDIO_UPTEMPO_HOUSE || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/uptempohouse.mp3',
    EARLY_MAY: import.meta.env.VITE_AUDIO_EARLY_MAY || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/may2.mp3',
    LOW_LIGHT: import.meta.env.VITE_AUDIO_LOW_LIGHT || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/hrrach.mp3',
    THIRD_PROGRESSION: import.meta.env.VITE_AUDIO_THIRD_PROGRESSION || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/prog3.mp3',
    JUNE_HOUSE: import.meta.env.VITE_AUDIO_JUNE_HOUSE || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/junehouseset.mp3',
    SOFT_PROGRESSION: import.meta.env.VITE_AUDIO_SOFT_PROGRESSION || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/proghouse.mp3',
    SLOW_RETURN: import.meta.env.VITE_AUDIO_SLOW_RETURN || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/downtempo622.mp3',
    MINIMAL_ORGANIC: import.meta.env.VITE_AUDIO_MINIMAL_ORGANIC || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/minimalandorganichouse.mp3',
    THE_LONG_CLIMB: import.meta.env.VITE_AUDIO_THE_LONG_CLIMB || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/prog.mp3',
    THE_SKY_CALLS: import.meta.env.VITE_AUDIO_THE_SKY_CALLS || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/theskycalls.mp3',
    FUTURE_SMILES: import.meta.env.VITE_AUDIO_FUTURE_SMILES || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/futuresmiles.mp3',
    GROUND_BENEATH: import.meta.env.VITE_AUDIO_GROUND_BENEATH || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/ohouse817.mp3',
    WALKING_BACKWARDS: import.meta.env.VITE_AUDIO_WALKING_BACKWARDS || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/walkingbackwards.mp3',
    FIRST_OF_JUNE: import.meta.env.VITE_AUDIO_FIRST_OF_JUNE || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/june1.mp3',
    MARCH_LIGHT: import.meta.env.VITE_AUDIO_MARCH_LIGHT || 'https://linturomusic.s3.us-west-2.amazonaws.com/sets/mar11.mp3',
  },

  // Video file URLs (obfuscated in production)
  VIDEO_FILES: {
    VIDEO1: import.meta.env.VITE_VIDEO_FILE_1 || 'https://linturomusic.s3.us-west-2.amazonaws.com/wourldtourradioclip.mp4',
    VIDEO2: import.meta.env.VITE_VIDEO_FILE_2 || 'https://linturomusic.s3.us-west-2.amazonaws.com/worldtourradioclip2.mp4',
    VIDEO3: import.meta.env.VITE_VIDEO_FILE_3 || 'https://linturomusic.s3.us-west-2.amazonaws.com/rooftopclip.mp4',
    VIDEO5: import.meta.env.VITE_VIDEO_FILE_5 || 'https://linturomusic.s3.us-west-2.amazonaws.com/techHouseClip.mp4',
    VIDEO6: import.meta.env.VITE_VIDEO_FILE_6 || 'https://linturomusic.s3.us-west-2.amazonaws.com/patternsVisualMix.mp4',
    ETERNAL_BEGINNING: import.meta.env.VITE_VIDEO_ETERNAL_BEGINNING || 'https://linturomusic.s3.us-west-2.amazonaws.com/eternal1-thsbeginning.mp4',
    ETERNAL_BEGINNING_POSTER: import.meta.env.VITE_VIDEO_ETERNAL_BEGINNING_POSTER || 'https://linturomusic.s3.us-west-2.amazonaws.com/eternal1-thsbeginning.jpg',
    CITY_STREETS: import.meta.env.VITE_VIDEO_CITY_STREETS || 'https://linturomusic.s3.us-west-2.amazonaws.com/citystreets.mp4',
    CITY_STREETS_POSTER: import.meta.env.VITE_VIDEO_CITY_STREETS_POSTER || 'https://linturomusic.s3.us-west-2.amazonaws.com/citystreets.jpg',
    ZOE: import.meta.env.VITE_VIDEO_ZOE || 'https://linturomusic.s3.us-west-2.amazonaws.com/zoe.mp4',
    ZOE_POSTER: import.meta.env.VITE_VIDEO_ZOE_POSTER || 'https://linturomusic.s3.us-west-2.amazonaws.com/zoe.jpg',
    REC059_SMILE_GLITCH: import.meta.env.VITE_VIDEO_REC059_SMILE_GLITCH || 'https://linturomusic.s3.us-west-2.amazonaws.com/rec059-smile-glitch.mp4',
    REC059_SMILE_GLITCH_POSTER: import.meta.env.VITE_VIDEO_REC059_SMILE_GLITCH_POSTER || 'https://linturomusic.s3.us-west-2.amazonaws.com/rec059-smile-glitch.jpg',
    LINTURO_GLITCH: import.meta.env.VITE_VIDEO_LINTURO_GLITCH || 'https://linturomusic.s3.us-west-2.amazonaws.com/linturo-glitch.mp4',
    LINTURO_GLITCH_POSTER: import.meta.env.VITE_VIDEO_LINTURO_GLITCH_POSTER || 'https://linturomusic.s3.us-west-2.amazonaws.com/linturo-glitch.jpg',
    REC084_SEPT_LOOP: import.meta.env.VITE_VIDEO_REC084_SEPT_LOOP || 'https://linturomusic.s3.us-west-2.amazonaws.com/rec084-sept-loop.mp4',
    REC084_SEPT_LOOP_POSTER: import.meta.env.VITE_VIDEO_REC084_SEPT_LOOP_POSTER || 'https://linturomusic.s3.us-west-2.amazonaws.com/rec084-sept-loop.jpg',
    THE_COLORS_WITHIN: import.meta.env.VITE_VIDEO_THE_COLORS_WITHIN || 'https://linturomusic.s3.us-west-2.amazonaws.com/the-colors-within.mp4',
    THE_COLORS_WITHIN_POSTER: import.meta.env.VITE_VIDEO_THE_COLORS_WITHIN_POSTER || 'https://linturomusic.s3.us-west-2.amazonaws.com/the-colors-within.jpg',
  },
  
  // App metadata
  APP_NAME: 'Linturo',
  APP_VERSION: import.meta.env.VITE_APP_VERSION || '1.0.0',
};